name: "Really coolname Generator"
description: "generate a cool name like crazy-red-baboon. Now with env vars fix!"
inputs:
  separator:
    description: "What separator to use"
    required: true
    default: "-"
  length:
    description: "How many words in the name"
    required: true
    default: "2"
  style:
    description: "Name output case style"
    required: true
    default: "lowerCase"
outputs:
  name:
    description: "The generated random name output."
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "activity"
  color: "blue"
